# Site settings
title: riderm4n
email: iam@riderm4n.com
description: > # this means to ignore newlines until "baseurl:"
  a kamen coder, kamen rider who code for henshin
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://riderm4n.com" # the base hostname & protocol for your site
github_username:  riderm4n


# Build settings
markdown: kramdown

#Default var
defaults:
-
  scope:
    path: ""
    type: "posts"
  values:
    comments: "true"
    layout: "post"
-
  scope:
    path: ""
    type: "posts"
  values:
    featured: "false"
    layout: "post"



collections :
    products :
        output : true
        permalink: /shop/:path/

  
